// Generated by CoffeeScript 1.9.1
define('mods/common/header',['smcore','_base/class','_tpl/header'],function(smcore, Class, hdTpl) {
  var TplInit, _timer;
  TplInit = Class.create({
    initialize: function() {
      var $body, $cartBtn, $hd_user;
      $body = $('body');
      $hd_user = $('#hd_user');
      $cartBtn = $('.header_icon_wrap');
      this.tpl_cartbtn = $(hdTpl.cartbtn);
      this.tpl_user = $(hdTpl.userinfo);
      this.tpl_cartlist = $(hdTpl._cartlist);
      this.tpl_user.appendTo($hd_user);
      this.tpl_cartbtn.appendTo($cartBtn);
      return this.tpl_cartlist.appendTo($body);
    }
  });

  /*模板实例化 */
  new TplInit();
  _timer = null;

  /*header_user的vm模型 */
  _VM_.header_user = smcore.define({
    $id: "header_user",
    tpl_tips: "tpl_ggmod_userinfo",
    userInfo: {},
    isLogin: false,
    render: function() {
      return this.innerHTML;
    }
  });

  /*header_cart按钮的vm模型 */
  _VM_.header_cart = smcore.define({
    $id: "header_cart",
    tpl_cart: "",
    cartInfo: {},
    isOn: false,
    render: function() {
      return this.innerHTML;
    },
    movein: function() {
      if (_timer) {
        clearTimeout(_timer);
      }
      _VM_.header_cart.tpl_cart = "tpl_header_cartlist";
      _VM_.header_cart.isOn = true;
      return $('.cart_content_all').slideDown();
    },
    moveout: function() {
      return _timer = setTimeout(function() {
        _VM_.header_cart.tpl_cart = "";
        _VM_.header_cart.isOn = false;
        return $('.cart_content_all').slideUp();
      }, 1500);
    }
  });
  return _VM_;
});
