// Generated by CoffeeScript 1.10.0
var _, _cdn, _cdnDomain, _cfgFile, _config, _env, _host, _isDebug, _mod, _port, _root, _ver, _view, args, config, defaultConfig, fs, key, path, ref, setting, val;

fs = require('fs');

path = require('path');

_ = require('lodash');

args = require('yargs').argv;

defaultConfig = require(path.join(__dirname, '../config.json'));

_cfgFile = global.Cache['cfgFile'];

_config = require(_cfgFile);

config = _.assign({}, defaultConfig, _config);

_root = process.cwd() + '/';

_isDebug = args.d || args.debug || false;

_env = args.e || args.env || "local";

_cdn = args.c || args.cdn || config.cdnDomain;

_ver = args.v || args.ver || config.version;

_host = args.h || args.host || config.host;

_port = args.p || args.port || config.port;

_mod = args.m || args.mod;

_view = args.view || config.view;

if (config.cdnDomain !== _cdn) {
  config.cdnDomain = _cdn;
}

if (config.version !== _ver) {
  config.version = _ver;
}

if (config.host !== _host) {
  config.host = _host;
}

if (config.port !== _port) {
  config.port = _port;
}

if (_mod) {
  config.coreJs.mods = _mod.split(',');
}

if (_view) {
  config.view = _view;
}

fs.writeFileSync(_cfgFile, JSON.stringify(config, null, 4), 'utf8');

_cdnDomain = _cdn ? _env + "." + _cdn : config.host + ":" + config.port;

if (_env === "www") {
  _cdnDomain = config.cdnDomain;
}

setting = _.assign({}, config);

setting.root = _root;

setting.env = _env;

setting.ver = _ver;

setting.force = !!args.force || !!args.f || false;

setting.isDebug = setting.force ? true : _isDebug;

setting.cdnDomain = "//" + _cdnDomain + "/";

setting['paths'] = {};

ref = config.paths;
for (key in ref) {
  val = ref[key];
  setting['paths'][key] = val + '/';
}

global.Cache = global.Cache || (global.Cache = {});

(function() {
  var _Cfg, ref1;
  _Cfg = setting;
  ref1 = _Cfg.paths;
  for (key in ref1) {
    val = ref1[key];
    _Cfg[key + "Path"] = val;
  }
  return global.Cache['gOpts'] = _Cfg;
})();

module.exports = setting;
