// Generated by CoffeeScript 1.9.1

/*初始化ibar模板 */
define(['_base/class', '_tpl/ibar'], function(Class, Tpl) {
  var tplInit;
  return tplInit = Class.create({
    initialize: function() {
      var $body;
      $body = $("body");

      /*
       * 注入主模块，注入依赖
       */

      /* 载入主模板 */
      this.tpl_main = $(Tpl.main);

      /* 载入子模板 - 用户信息 */
      this.tpl_login = $(Tpl._login);

      /* 载入子模板 - 购物车信息 */
      this.tpl_cart = $(Tpl._cart);

      /* 载入子模板 - 我的财产 */
      this.tpl_asset = $(Tpl._asset);

      /* 载入子模板 - 我的心愿单 */
      this.tpl_favorite = $(Tpl._favorite);

      /* 载入子模板 - 我的浏览记录 */
      this.tpl_history = $(Tpl._history);

      /* 载入子模板 - 附属信息 */
      this.tpl_recharge = $(Tpl._recharge);

      /* 将模板注入到页面中 */
      this.tpl_main.appendTo($body);
      this.tpl_login.appendTo($body);
      this.tpl_cart.appendTo($body);
      this.tpl_asset.appendTo($body);
      this.tpl_favorite.appendTo($body);
      this.tpl_history.appendTo($body);
      return this.tpl_recharge.appendTo($body);
    }
  });
});
